import Head from "next/head";
import Image from "next/image";
import mylogo from "../public/myicon.svg";
import me from "../public/meHD.png";
import { BsFillMoonStarsFill, BsJournals } from "react-icons/bs";
import fb from "../public/facebook-rounded-svgrepo-com.svg";
import insta from "../public/instagram-svgrepo-com.svg";
import linked from "../public/linkedin-linked-in-svgrepo-com.svg";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import AOS from "aos";
import "aos/dist/aos.css";
import React, { useEffect } from "react";
import html from "../public/html5.svg";
import css from "../public/css3.svg";
import tailwind from "../public/tailwind.svg";
import js from "../public/javascript.svg";
import nextjs from "../public/next.svg";
import tech from "../public/troubleshoot-svgrepo-com.svg";

import chess from '../public/chess-svgrepo-com.svg';
import basket from '../public/basketball-goal-7-svgrepo-com.svg'
import games from '../public/games-svgrepo-com.svg'
import eat from '../public/eating-svgrepo-com.svg'
import num from '../public/phone-number-svgrepo-com.svg' 
import email from '../public/email-svgrepo-com.svg'
import send from '../public/send-03-svgrepo-com.svg'
export default function Home() {

  const [darkMode, setDarkMode] = useState(false);


  useEffect(() => {
    AOS.init();
  }, []);
  return (
    <div class={darkMode ? "dark" : ""}>
      <Head>
        <title>Carl's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-blue-50 h-screen ">
        <nav className="p-[40px]  md:p-[50px] fixed top-0 left-0 right-0 ">
          <section className="items-center flex justify-between ">
            <a href="#first">
              <Image
                className=" ease-in-out duration-300 hover:scale-125  cursor-pointer w-full max-w-[100px]"
                src={mylogo}
              ></Image>
            </a>

            <ul className="pl-[30px] flex justify-evenly md:w-[350px]">
              <li className=" hover:font-bold hover:shadow-xl ease-in-out duration-300 hover:scale-125 text-[20px] mr-[20px]">
                <a href="#second">Skills</a>
              </li>
              <li className="hover:font-bold hover:shadow-xl ease-in-out duration-300 hover:scale-125  text-[20px] mr-[20px]">
                <a href="#third">About</a>
              </li>
            </ul>
          </section>
        </nav>
        <section id="first" className=" bg-blue-50">
          <div className="
        pt-[250px]
        md:pt-0
         md:flex
          h-screen  justify-center md:justify-between items-center m-auto max-w-[1000px] text-center 
           ">
            <div className="text-2xl justify-center  md:inline-block md:text-4xl max-w-[1000px] min-w-[300px]">
              Hi!, I'm{" "}
              <strong className="text-[30px] md:text-[40px]">Carl Nielsen Santos</strong>
              <span className="text-xl md:text-2xl"> aspiring Web Developer</span>

              <div className="flex mt-[10px] md:mb-0  items-center md:m-[20px] w-full justify-center min-w-[300px]">
                
                <a
                  href="https://www.facebook.com/SantosCarlNielsen"
                  target="_blank"
                >
                  <Image
                    className="opacity-75 hover:scale-125 ease-in-out duration-300 mr-[5px] w-[25px] hover:opacity-100"
                    src={fb}
                  ></Image>
                </a>
                <a href="https://www.instagram.com/engrnissin/" target="_blank">
                  <Image
                    className="opacity-75 hover:scale-125 ease-in-out duration-300 w-[25px] hover:opacity-100"
                    src={insta}
                  ></Image>
                </a>

                <a
                  href="https://www.linkedin.com/in/carl-nielsen-santos-7971b724a"
                  target="_blank"
                >
                  <Image
                    className="opacity-75 hover:scale-125 ease-in-out duration-300 ml-[5px] w-[25px] hover:opacity-100"
                    src={linked}
                  ></Image>
                </a>
              </div>
            </div>

            <div className="">
              <Image
                className=" ease-in-out duration-300 hover:scale-125 
                w-full h-auto md:rounded-full 
                md:w-full
                md:max-w-[500px] "
                src={me}
              ></Image>
            </div>
          </div>
        </section>

        <section
          id="second"
          className=" bg-blue-50 pt-[100px] h-screen  md:pt-[200px] md:pl-[70px] md:pr-[85px]"
        >
          <p className="pl-[20px] font-bold md:text-[60px] mb-[20px]">Skills</p>
          <div  className=" mx-auto space-y-2 md:space-y-0 md:gap-10 md:grid md:grid-cols-3">
            <div className="
            
            ml-[30px]
            mr-[30px]
            shadow-xl rounded-xl ease-in-out duration-300 hover:scale-125  
            pl-[5px] pr-[10px] flex items-center  bg-blue-100 md:w-[420px] md:h-[200px]">
              <Image className="w-[50px] md:w-[150px] inline" src={html}></Image>

              <div className="text-[10px] md:text-[15px] ml-[10px] text-justify">
                I've been using HTML for past 3months and I love it. I've been
                using HTML for past the 3 months and I love it. I watched video
                tutorial to learn the basic fundamentals in HTML.
              </div>
            </div>
            <div className=" ml-[30px]
            mr-[30px] shadow-xl rounded-xl ease-in-out duration-300 hover:scale-125 
            pl-[5px] pr-[10px] flex items-center  bg-blue-100  md:w-[420px] md:h-[200px]">
              <Image className="w-[50px] md:w-[150px] inline" src={css}></Image>
              <div className="text-[10px] md:text-[15px] ml-[10px] text-justify">
                With the help of CSS I can build a basic website with some
                transitions and design but the responsiveness is still
                developing since I'm a newbie in web developing.
              </div>
            </div>
            <div className=" ml-[30px]
            mr-[30px] shadow-xl rounded-xl ease-in-out duration-300 hover:scale-125 
            pl-[5px] pr-[10px] flex items-center bg-blue-100  md:w-[420px] md:h-[200px]">
              <Image className="w-[50px] md:w-[150px] inline" src={tailwind}></Image>
              <div className="text-[10px] md:text-[15px] ml-[10px] text-justify">
                After learning Html and CSS, my friend introduce me TailwindCSS
                and I feel confuse when he said that tailwindCSS is much better
                easy than classic CSS, so in building my portfolio I used
                tailwind.
              </div>
            </div>
            <div className=" ml-[30px]
            mr-[30px] shadow-xl rounded-xl ease-in-out duration-300 hover:scale-125 
            pl-[5px] pr-[10px] flex items-center bg-blue-100  md:w-[420px] md:h-[200px]">
              <Image className="w-[50px] md:w-[150px] inline" src={js}></Image>
              <div className="text-[10px] md:text-[15px] ml-[10px]  text-justify">
                I have basic knowledge in JavaScript when I used it in my
                previous project in school but If I rate myself in scale of 1 to
                5 my knowledge in JS is 2.
              </div>
            </div>
            <div className="ml-[30px]
            mr-[30px] shadow-xl rounded-xl ease-in-out duration-300 hover:scale-125
            pl-[10px] pr-[10px] flex items-center bg-blue-100  md:w-[420px] md:h-[200px]">
              <Image className="w-[50px] md:w-[150px] inline" src={nextjs}></Image>
              <div className="text-[10px] md:text-[15px] ml-[10px] text-justify">
                I've been using this framework for two months. and I like it
                since your work may be easily deployed in their partner vercel.
                I can simply adapt this framework because there are several
                tutorials on YouTube. 
              </div>
            </div>
            <div className=" ml-[30px]
            mr-[30px] shadow-xl rounded-xl ease-in-out duration-300 hover:scale-125 
            pl-[5px] pr-[10px] flex items-center bg-blue-100  md:w-[420px] md:h-[200px]">
              <Image className="w-[50px] md:w-[150px] inline" src={tech}></Image>
              <div className="text-[10px] md:text-[15px] ml-[10px] text-justify">
                I can do basic formatting of computer, installation, basic troubleshooting and I'm a NC II CSS holder so I can do basic network configurations.
              </div>
            </div>
          </div>
        </section>

        <section id="third" 
        className=" bg-blue-50 pt-[100px] h-screen  md:pt-[200px] md:pl-[70px] md:pr-[45px]">

          <div className="">
            <p className="pl-[20px]  font-bold md:text-[40px] mb-[20px]">About Me</p>
            <p className="indent-5 text-[10px] text-justify md:indent-20 md:text-xl pl-[20px] pr-[20px]">I'm Carl Nielsen A. Santos, 21 years old from Taytay Rizal, a college student taking a 
            Bachelor of Science in Computer Engineering in Rizal Technological University Boni Campus. I'm a hardworking person and I love studying some things that make me confuse
            and I'm a person that take all the challenges in positive way, since I am a positive person.
            </p>
            <p className="mt-[10px] indent-5 text-[10px] text-justify md:indent-20 md:text-xl pl-[20px] pr-[20px]">
              My hobby is playing chess my all time favourite since I was grade 6 and become a representative in our school until I graduated in Senior High School.
              I love playing chess because of what improvement I get, for example in critical thinking skills. In playing chess you
              will improve it the way that you think in game seriously and thinking in a serious way makes us a better person, in what way?
              For example in game of chess before you move you will need think because every wrong move your opponent will take that as advantage to defeat you, just 
              like in life you will need to think before you act. Other hobby is playing chess, online games and computer games with my friends and lastly I love eating and
              I consider it as my hobby.
            </p>
            <p className="text-2xl pl-[20px]"></p>
          </div>
          <div  className="pb-[20px] mt-[30px] md:mt-[50px] flex justify-evenly max-w-[1450px]">
              <Image
              className=" w-[40px] md:w-[100px] md:mr-[20px] ease-in-out duration-300 hover:scale-125"
              src={chess}></Image>
               <Image
              className=" w-[40px] md:w-[100px] md:mr-[20px] ease-in-out duration-300 hover:scale-125"
              src={eat}></Image>
               <Image
              className="w-[40px] md:w-[100px] md:mr-[20px] ease-in-out duration-300 hover:scale-125"
              src={basket}></Image>
               <Image
              className=" w-[40px] md:w-[100px] md:mr-[20px] ease-in-out duration-300 hover:scale-125"
              src={games}></Image>
          </div>
          <div className="border-t-2
          
          pt-[10px]
          md:pt-[50px]
          md:flex md:justify-around md:mt-[30px]">
            <div className="">
                <p className="w-full justify-center text-center  md:text-[30px] font-bold md:mb-[40px]">Contact</p>
                <div className="justify-center text-center md:ml-[20px] flex md:justify-evenly md:text-center md:w-[170px] ">
                  <Image
                  className="w-[10px] md:ml-[110px] inline md:mb-[30px] md:w-[30px]" 
                  src={email}></Image>
                  <p className="text-[10px] pl-[5px] md:pl-[10px] md:text-lg italic inline-block">santoscarlnielsen6@gmail.com</p>
                </div>
                <div className="justify-center  md:ml-[20px] flex md:justify-evenly text-center md:w-[170px] ">
                  <Image
                  className="w-[10px] inline md:mb-[30px] md:w-[30px]" 
                  src={num}></Image>
                  <p className="pl-[5px] text-[10px] md:pl-[10px] md:text-lg italic inline">+639077389580</p>
                </div>
            </div>
              <div className="mt-[10px]  justify-center text-center md:text-[30px] font-bold mb-[40px]">
                <p>Send Message</p>
                <p className="text-[8px] md:text-sm">note: not yet done in this section</p>
                <input 
                className="text-[9px] ml-[5px] bg-blue-50 md:mr-[20px] md:pl-[10px] md:text-lg font-normal border-gray-400 border-[1px] md:w-[200px] md:h-[40px]"
                placeholder="Name"
                type="text" />
                <input 
                className="text-[9px] mb-[5px] md:inline bg-blue-50 md:pl-[10px] md:text-lg font-normal border-gray-400 border-[1px] md:w-[300px] md:h-[40px]"
                placeholder="Email "
                type="text" />
               
                  <Image 
                  className="w-[10px] ease-in-out duration-300 
                  hover:scale-125 ml-[10px] inline md:w-[40px]"
                  src={send}></Image>
                <div className="flex justify-center justify-items-end">
                  <input 
                  className="w-[200px] pb-[70px] text-[10px] break-all text-justify md:mt-[20px] block pt-[5px]
                  bg-blue-50 pl-[10px] md:text-lg font-normal border-gray-400 border-[1px] md:w-[570px] md:pb-[120px]"
                  placeholder="Compose a message "
                  type="text" /> 
                  
                </div>
                
              </div>
          </div>
        
        </section>
      </main>
    </div>
  );
}
